### PR TITLE
Add support for copying entity to clipboard #8

### PR DESCRIPTION
**Pull request by roxk**
connect #8 
requires #11

This is an initial implementation, some keyboard/identifier/type combination would produce incorrect result but this is a start.

It is slow because it's always generating all idl files and my project has a ton. I have another PR cooking to only compile the editing file (passed via `IDLFile`).

https://user-images.githubusercontent.com/16918354/197392727-affb8bff-eee0-47f2-95d3-b51dc5da033d.mp4

### CODE REVIEW

**Comment by madskristensen** [comment]
This is pretty awesome. Is it ready for merging? You mentioned it is slow

**Comment by roxk** [comment]
Yes, it should be ready to merge. 

The slowness came from always building everything, not inherently related to the implementation of this feature. With incremental build working it's now pretty fast. The only real work triggered per command is now cppwinrt. I have not figured out a reliable way to map from winmd -> the header file (due to namespace prefix) so cppwinrt still builds everything now. Despite that, the current speed is at least workable.

Bottomline, it is as fast as clicking generate header file.

**Comment by roxk** [comment]
Now that I think of it, one member in the uwp community discord mentioned that the name is confusing. Should the command be renamed to just "Copy Entity Header"?

**Comment by madskristensen** [comment]
Thanks. Feel free to send PR with updated text. Btw, thank you so much for this!!!

**Pull request merged**
